version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: my-tailor-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_tailor_db

